title: Nikhil Reddy Satti # your name (or website title) here
logo: "Image/Logo.png?raw=true" # your photo (or logo) here
font-family: Times New Roman
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data-driven problem solver with expertise in C, Java, Python, R, and SQL. Skilled in using Tableau, KNIME, Azure, and AWS to tackle real-world challenges through regression analysis, data clustering, and more.
  <br><br>
  <a href="https://www.linkedin.com/in/nikhilreddysatti/">LinkedIn</a> 
  /
  <a href="https://github.com/NikhilReddySatti/Data-Analyst-Portfolio/blob/main/Resume_NikhilReddySatti.pdf">Resume</a> 
  /
  <a href="https://github.com/NikhilReddySatti?tab=repositories">GitHub</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-T05XD565QB # your Google Analytics tracking ID here
